- name: Singapore Government Tech Stack
  description: A common platform that streamlines and simplifies the development process
  items:
    - Overview
    - Asynchronous Data Exchange
    - APEX
    - Cloud File Transfer
    - Container Stack
    - Corppass
    - DECADA IoT Tech Stack
    - Identiface
    - Login
    - Myinfo
    - Personalise
    - SHIP-HATS
    - Singapore Government Design System
    - StackOps
    - VAS
    - Verify
    - WOGAA

- name: What's New
  description: Discover the latest product additions to the Singapore Government Developer Portal here
  items:
    - Overview
    - Cloud File Transfer
    - OurSG
    - TradeTrust
